Add testbench for Pluto
analogdevicesinc/testbenches pull request #100
Opened 2024-04-30 11:25 UTC by podgori

This commit adds a new testbench for Pluto in 2R2T mode, including the Phaser setup and testing.

2024-05-13 08:37 UTC, IstvanZsSzekely requested changes

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +  end
The variable `rate` in this case is a constant. 
The integer makes it a 4-state type. Using `int` in this testbench is better, because it is only a 2-state type and the variable is not used for non-binary operation. 
With this, the `initial begin` part can be removed and the value can be assigned regularly like the previous values.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +  parameter TDD1 = `AXI_AD9361_BA + 'h12_00 * 4;
Is there a plan to have a testbench that can configure the test_program later on? If not, localparam would be a better option, to prevent edits from the instantiating module.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    #1us;
Please call `env.sys_reset();` instead.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    phaser_test;
Please use brackets to highlight function calls. Same goes for the other instances further in the code.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +              `SET_DAC_CHANNEL_REG_CHAN_CNTRL_7_DAC_DDS_SEL(9));
Missing indentation. Please update the other instances as well.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +   #1000;
Please specify the time unit as well. Same goes for the rest.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +                           int max_sample = 2048
These values should be left unassigned so it can prevent errors when someone tries to call the function without setting these parameters.

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +  parameter RX1_CHANNEL = `AXI_AD9361_BA;
These have the same value. Is there a reason to create 2 variables here?

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +  parameter TX1_CHANNEL = `AXI_AD9361_BA + 32'h0000_4000;
These have the same value. Is there a reason to create 2 variables here?

2024-05-13 08:37 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    `TH.`SSI_CLK.inst.IF.set_clk_frq(.user_frequency(80000000));
The clock frequency doesn't match the value from the block design

2024-08-07 11:04 UTC, podgori commented on pluto/tests/test_program.sv
> +  end
With the latest changes, `rate` is now updated during runtime depending on the selected mode.

2024-08-07 11:05 UTC, podgori commented on pluto/tests/test_program.sv
> +  parameter TDD1 = `AXI_AD9361_BA + 'h12_00 * 4;
Updated the test_program to use localparams.

2024-08-07 11:05 UTC, podgori commented on pluto/tests/test_program.sv
> +    #1us;
Done

2024-08-07 11:05 UTC, podgori commented on pluto/tests/test_program.sv
> +    phaser_test;
Done

2024-08-07 11:05 UTC, podgori commented on pluto/tests/test_program.sv
> +              `SET_DAC_CHANNEL_REG_CHAN_CNTRL_7_DAC_DDS_SEL(9));
Done

2024-08-07 11:06 UTC, podgori commented on pluto/tests/test_program.sv
> +   #1000;
Done

2024-08-07 11:06 UTC, podgori commented on pluto/tests/test_program.sv
> +                           int max_sample = 2048
Done

2024-08-07 11:09 UTC, podgori commented on pluto/tests/test_program.sv
> +  parameter TX1_CHANNEL = `AXI_AD9361_BA + 32'h0000_4000;
This is to differentiate between the register sections, even though the base addresses are the same. Please refer to the register map table of AXI_AD9361.

2024-08-07 11:12 UTC, podgori commented on pluto/tests/test_program.sv
> +    `TH.`SSI_CLK.inst.IF.set_clk_frq(.user_frequency(80000000));
I suggest leaving both: in BD you can find the max clock frequency for AD9361, whereas in the test program I have updated the frequency to be specific for Pluto.

2024-08-07 11:12 UTC, podgori commented on pluto/tests/test_program.sv
> +  parameter RX1_CHANNEL = `AXI_AD9361_BA;
Please check the below comment.

2024-08-07 11:41 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    `TH.`SSI_CLK.inst.IF.set_clk_frq(.user_frequency(80000000));
Can this testbench be used for testing AD9361 as well as Pluto with the same block design and test program? If that is the case, I would suggest creating 2 configuration files for each so both can be tested.

2024-08-07 11:45 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    phaser_test;
Please add brackets to function declarations as well.

2024-08-07 11:49 UTC, IstvanZsSzekely requested changes

2024-08-07 11:49 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +    rate = r1_mode ? 1 : 2;
Suggestion: `rate = r1_mode ? 0 : 1;`

2024-08-07 11:49 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +              `SET_DAC_COMMON_REG_RATECNTRL_RATE(rate-1));
Suggestion: `SET_DAC_COMMON_REG_RATECNTRL_RATE(rate));`

2024-08-07 11:49 UTC, IstvanZsSzekely commented on pluto/tests/test_program.sv
> +   // Put RX in reset
Indentation misaligned

2024-08-07 12:11 UTC, podgori commented on pluto/tests/test_program.sv
> +    `TH.`SSI_CLK.inst.IF.set_clk_frq(.user_frequency(80000000));
The use of maximum frequency should be integrated in the fmcomms2 testbench. This testbench should only verify the features of Pluto.

2024-08-07 12:23 UTC, podgori commented on pluto/tests/test_program.sv
> +    rate = r1_mode ? 1 : 2;
Let's keep it as it is; in the fmcomms2 testbench it is computed in a similar way.

2024-08-07 12:23 UTC, podgori commented on pluto/tests/test_program.sv
> +              `SET_DAC_COMMON_REG_RATECNTRL_RATE(rate-1));
Let's keep it as it is; in the fmcomms2 testbench it is computed in a similar way.

2024-08-07 12:49 UTC, podgori commented on pluto/tests/test_program.sv
> +   // Put RX in reset
Fixed

2024-08-07 12:49 UTC, podgori commented on pluto/tests/test_program.sv
> +    phaser_test;
Done

2024-09-26 09:14 UTC, podgori commented
Updated the testbench to test and support the latest changes in Pluto:
https://github.com/analogdevicesinc/hdl/pull/1468

2024-10-02 13:41 UTC, gastmaier approved these changes
The run is ok, but the log is drown with the following warning (2024.1:
```
Warning: [AXI DDR stub agent_mem_model] (axi_vip_pkg.xil_axi_slv_mem_model(C_AXI_WDATA_WIDTH=512,C_AXI_RDATA_WIDTH=512,C_AXI_SUPPORTS_NARROW=0,C_AXI_HAS_REGION=0)::backdoor_memory_write_4byte) 208305 ns : Addr(0xffffffff80001ffc) is out of range(0xffffffff). Address will be truncated.
Time: 208305 ns  Iteration: 7  Process: /system_tb/test/tdd_test/Block482_231  Scope: axi_vip_pkg.xil_axi_slv_mem_model(C_AXI_WDATA_WIDTH=512,C_AXI_RDATA_WIDTH=512,C_AXI_SUPPORTS_NARROW=0,C_AXI_HAS_REGION=0)::backdoor_memory_write_4byte  File: /mnt/wsl/data/repos/hdl-100/testbenches/pluto/tests/test_program.sv Line: 14686
```

2024-10-02 14:53 UTC, IstvanZsSzekely approved these changes

2024-10-02 15:20 UTC, merged