SPI VIP
analogdevicesinc/testbenches pull request #103
Opened 2024-05-08 13:14 UTC by LBFFilho

Add a VIP for SPI. This should simplify tests for anything SPI-related, and allow us to have our SPI model code in a single place.

This uses an abstract class for connecting with the testbench environment, which is simpler than using a virtual interface like the Xilinx VIPs.

2024-05-08 19:09 UTC, gastmaier requested changes

2024-05-08 19:10 UTC, LBFFilho commented on common/sv/spi_vip/adi_spi_vip.sv
> +      assign IF.sclk = m_spi_sclk;
yes, they are, will fix

2024-05-08 19:14 UTC, LBFFilho commented on common/sv/spi_vip/Makefile
> +INTEL_DEPS += adi_spi_vip_hw.tcl
will put as TODO

2024-05-08 19:20 UTC, LBFFilho commented on common/sv/s_spi_sequencer.sv
> +    adi_spi_agent agent;
I was trying to keep consistency, our other sequencers allow the user to call agent methods directly. I think it makes sense, conceptually: the sequencers should only see transactions, the agents handle lower level things.

That said, I also like the alternative (making wrappers for the agent's methods on sequencer), so maybe?

2024-05-13 11:26 UTC, IstvanZsSzekely requested changes

2024-05-13 11:26 UTC, IstvanZsSzekely commented on spi_engine/spi_environment.sv
> +    endtask
If the sub-class spi_environment doesn't do anything additional with the sys_reset, this can be left out.

2024-05-13 11:26 UTC, IstvanZsSzekely commented on spi_engine/spi_environment.sv
> +      super.start();
Reverse the order for these. The test_harness_env class in the start function starts the clocks and the basic modules, which in my opinion should be started first.

2024-05-13 11:26 UTC, IstvanZsSzekely commented on common/sv/spi_vip/adi_spi_vip.sv
> +  input   logic mon_spi_cs
Regarding this part, I believe it makes more sense to implement it like Xilinx did. Having this module as passthrough makes more sense than having just a monitor, since the passthrough module can act as a monitor, master or slave, without touching the block design. 
Yes, it will make our lives a bit more difficult inserting these between different modules, but it gives more flexibility to test parts individually inside the same testbench.

2024-05-14 07:48 UTC, IstvanZsSzekely requested changes

2024-05-14 07:48 UTC, IstvanZsSzekely commented on common/sv/spi_vip/spi_vip_if.sv
> +      begin
After the task is declared, begin...end is not necessary, as the `task` keyword signals the begin of the execution block. Same goes for the other tasks.

2024-05-14 07:48 UTC, IstvanZsSzekely commented on common/sv/spi_vip/spi_vip_if.sv
> +            disable fork;
Please add a fork guard, that safely disables the fork. Check [I3C](https://github.com/analogdevicesinc/testbenches/blob/9bbb0f541cf0aaec40f3831f6c7e5a32e79bcc0b/i3c_controller/tests/test_program.sv#L50). The external fork is the guarding fork, that prevents disable to kill unwanted processes.

2024-05-14 07:48 UTC, IstvanZsSzekely commented on common/sv/spi_vip/spi_vip_if.sv
> +      join
In the sequencers that we currently use, the forever loops were declared inside the tasks. Shall we keep the same structure in our codebase?

2024-05-14 07:48 UTC, IstvanZsSzekely commented on common/sv/spi_vip/spi_vip_if.sv
> +    task start();
Set stop_flag back to 0, so it can be restarted if needed.

2024-05-14 07:48 UTC, IstvanZsSzekely commented on common/sv/spi_vip/spi_vip_if.sv
> +          disable fork;
Add a fork guard.

2024-05-17 11:21 UTC, gastmaier requested changes

2024-05-17 12:26 UTC, LBFFilho commented on common/sv/spi_vip/adi_spi_vip.sv
> +     $fatal("Unsupported mode %s. Valid values are 0=SLAVE, 1=MASTER, 2=MONITOR. Only 0(SLAVE) is currently supported.",MODE);
we could, and it's better, but then that's another header for the IP and now we would have multiple copies of utils.svh on the hierarchy. I didn't put it since I didn't know if this was acceptable.

2024-05-17 12:27 UTC, LBFFilho commented on common/sv/spi_vip/spi_vip_if.sv
> +      this.mosi_mbx = new();
mailbox, see line 76

2024-05-17 12:29 UTC, LBFFilho commented on common/sv/spi_vip/spi_vip_if.sv
> +                $display("[SPI VIP] tx_miso: early exit due to unexpected CS inactive!");
Would love to standardize. I was thinking of having the instance name or a tag passed onto the parent class during instantiation. Macro would work too.

Why not an error: no good reason really, it should be.

2024-05-17 12:32 UTC, LBFFilho commented on common/sv/spi_vip/spi_vip_if.sv
> +    .CPOL         (CPOL),
It currently actually makes it hiZ with CS inactive (so you can have multiple SPI VIP slaves sharing miso/mosi). But yes, that's a nice idea (having a parameter to control which behaviour). Was planning on introducing it toghether with https://github.com/analogdevicesinc/hdl/pull/1320

2024-05-17 13:53 UTC, gastmaier requested changes

2024-05-17 13:53 UTC, gastmaier commented on spi_engine/Makefile
> +SV_DEPS += ../common/sv/spi_vip/adi_spi_vip.sv
Lib deps shouldn't be listed here since they are already component.xml-timestamp-managed
```suggestion
```

2024-05-17 13:53 UTC, gastmaier commented on scripts/project-sim.mk
> +FORCE:
Dangling FORCE

2024-05-17 13:53 UTC, gastmaier commented on scripts/project-sim.mk
>  FORCE:
Dangling FORCE

2024-05-17 14:29 UTC, gastmaier commented
I think we have a pretty solid foundation for VIPs.
After this pr and the flock tb gets merged, we can work on some rough corners.

2024-05-21 12:26 UTC, gastmaier approved these changes
Reviewed c27beab3dcff8900894f6210a9e5935c911efbc7

2024-05-21 12:26 UTC, gastmaier commented on common/sv/spi_vip/spi_vip_if.sv
> +            $display("i=%0d",i);
`INFO?

2024-05-22 12:49 UTC, LBFFilho commented
I've updated the .gitignore based on the HDL repo. It's currently mostly a copy, so probably some room for improvement.

2024-05-23 18:47 UTC, LBFFilho commented
Switched to virtual interface, now the branch name is no longer exact.

2024-05-24 08:19 UTC, IstvanZsSzekely requested changes

2024-05-24 08:19 UTC, IstvanZsSzekely commented on common/sv/spi_vip/adi_spi_vip_pkg.sv
> +                                    SPI_VIP_DEFAULT_MISO_DATA ='hCAFE
It might be better for us to remove parameter default values from the list. Creating a class with default values might give us a lot of trouble, so forcing the user to add the parameter values at declaration will ensure proper functionality of the part. This was observed at parameterized regmap creation.

2024-05-24 08:19 UTC, IstvanZsSzekely commented on common/sv/spi_vip/adi_spi_vip_pkg.sv
> +                                    SPI_VIP_DEFAULT_MISO_DATA ='hCAFE
Same as previous one

2024-05-24 08:19 UTC, IstvanZsSzekely commented on common/sv/spi_vip/adi_spi_vip_pkg.sv
> +  `define SPI_VIP_PARAM_ORDER       SPI_VIP_MODE              ,\
6 different definitions for the SPI might be a bit of an overkill. Let's see if we can cut these down to a more reasonable level and see what can we do to the currently existing definitions as well.

2024-05-24 16:30 UTC, gastmaier approved these changes

2024-05-28 08:47 UTC, IstvanZsSzekely approved these changes

2024-05-28 12:01 UTC, LBFFilho commented
[celebrate]     Barbosa, Laez reacted to your message:
________________________________
From: IstvanZsSzekely ***@***.***>
Sent: Tuesday, May 28, 2024 8:47:42 AM
To: analogdevicesinc/testbenches ***@***.***>
Cc: Barbosa, Laez ***@***.***>; Author ***@***.***>
Subject: Re: [analogdevicesinc/testbenches] SPI VIP (PR #103)

[External]


@IstvanZsSzekely approved this pull request.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/analogdevicesinc/testbenches/pull/103*pullrequestreview-2082150647__;Iw!!A3Ni8CS0y2Y!4v-s7-ILCzDNpLNejOXwmsl8A4bw-B39WequY_mcJruQFPQgYX5yME5agCTvNnnMYKgZgFV75ZVYNBDDN1ug9jJ7Vyo$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ABUJCCK2VNGS24IIARWWDB3ZERAC5AVCNFSM6AAAAABHM6QWPSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBSGE2TANRUG4__;!!A3Ni8CS0y2Y!4v-s7-ILCzDNpLNejOXwmsl8A4bw-B39WequY_mcJruQFPQgYX5yME5agCTvNnnMYKgZgFV75ZVYNBDDN1ugaiyrE7c$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-05-28 12:31 UTC, merged