Axi dmac flock
analogdevicesinc/testbenches pull request #104
Opened 2024-05-20 13:52 UTC by gastmaier

Tests [#analogdevicesinc/hdl/1332](https://github.com/analogdevicesinc/hdl/pull/1332).
Add a VIP for IO.
Add AXI DMAC Framelock testbench.
Will merge conflict with #103 since adds the same changes to support libraries in this repo.
Uses "old" axi_dmac_pkg. Happy to update it to the new class based pkgs, either in this pr or in a future one.

2024-08-06 13:31 UTC, IstvanZsSzekely requested changes
Partial review
Some other notes: update the license header's year where it's needed

2024-08-06 13:31 UTC, IstvanZsSzekely commented on common/sv/dmac_api.sv
> +                        `SET_DMAC_CONTROL_FRAMELOCK(control[3]));
Align whitespace. Same for the rest

2024-08-06 13:31 UTC, IstvanZsSzekely commented on common/sv/dma_trans.sv
> +  endclass
Leave the closing name to indicate which class ends at this point

2024-08-06 13:31 UTC, IstvanZsSzekely commented on common/sv/io_vip/io_vip.sv
> +  output out
Specify bitwidth

2024-08-06 13:31 UTC, IstvanZsSzekely commented on common/sv/io_vip/io_vip.sv
> +  parameter MODE = 1, // 1 - driver, 0 - monitor
In most instances related to the VIP modes, I saw the use of Master-Slave naming scheme. 
Driver and Monitor is used in a different hierarchy level and this naming difference makes it easier distinguish the two

2024-08-07 09:07 UTC, IstvanZsSzekely requested changes
A note on the configurations. Configuration lists that are used for certain IPs can be passed to the system_bd just the same as other regular simple values with ad_project_params. On top of this, the scripts automatically create variables based on the configuration lists. You can check axi_tdd project for an example. I don't want you to change it unnecessarily, just to let you know about it.

2024-08-07 09:08 UTC, IstvanZsSzekely reviewed
I can't comment on the test program, as I don't know how Framelock works yet.

2024-08-26 06:40 UTC, IstvanZsSzekely requested changes
Unresolved a couple of changes and requested some others.

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +    env.sys_reset();
Starting the clocks and resetting the system should be done before the DMAs are accessed by the probe functions, between the environment start and run functions.

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program_frame_delay.sv
> +    env.sys_reset();
Same as in test_program

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program_frame_delay.sv
> +    $display("Testbench done!");
Display -> INFO

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program_frame_delay.sv
> +        #10;
Please specify the time unit

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program_frame_delay.sv
> +    #100;
Please specify the time unit

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program_frame_delay.sv
> +    #fperiod;
Please specify time unit as in test_program

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +        #10;
Please specify time unit

2024-08-26 06:40 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +    #100;
Please specify time unit

2024-08-26 12:15 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +    int dst_clk = 250000000
Please specify the which parameters are input and which are output for the tasks.

2024-08-26 12:47 UTC, IstvanZsSzekely requested changes
When looking into the testbench, I saw something weird with the tlast signal. When running cfg2_fsync configuration with test_program_frame_delay, after a single test was finished running, on the monitoring AXI Stream interface the tlast signal was not asserted, meaning that the packet was not transferred. Is this a framelock specific feature that causes the tlast not being asserted or something else?

2024-08-26 12:47 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +    env.dst_axis_seq.user_gen_tready();
Please set the Ready signal generation to be stable high with `set_mode(XIL_AXI4STREAM_READY_GEN_NO_BACKPRESSURE);` before starting up the ready signal generation. By default it is set to be randomized. 
In the testbench I saw that the tready was switching on both edges of a clock.

2024-08-26 16:37 UTC, gastmaier commented on dma_flock/tests/test_program.sv
> +    env.dst_axis_seq.user_gen_tready();
Oh thanks.

About tlast
The scoreboard looks for the start of frame, at the first beat first pixel, and
the test program roughly estimates how much time it would the frame to transfer and waits.
So the task and test program may finish (shutdown the env) before the frame is consumed, not generating the fourth tlast.

2024-08-27 08:21 UTC, IstvanZsSzekely commented on dma_flock/tests/test_program.sv
> +    env.dst_axis_seq.user_gen_tready();
For the tlast, not being interested in looking at it coming or not is fair enough. However, I'd still want to see the last packet arriving as well and only after that stopping the DMA. This way, it's clear where one test starts and finishes on all data paths. I'll leave it up to you to decide if you want to make the changes to complete the transfer in this PR or in a future one.

2024-09-11 13:25 UTC, IstvanZsSzekely approved these changes
Structurally and functionally everything seems to be good. I didn't check the the Framelock functionality in detail, so can't comment on the stimulus itself. 
Tested, working.

2024-11-19 21:44 UTC, merged