ad9083: Add testbench
analogdevicesinc/testbenches pull request #12
Opened 2021-07-20 11:43 UTC by sarpadi

2021-07-20 12:37 UTC, ronagyl requested changes

2021-07-20 12:37 UTC, ronagyl commented on ad9083/tests/test_program.sv
> +//    env.mng.RegWrite32(`TX_DMA+32'h408, 32'h00000001); // Submit transfer DMA
This section of code can be removed.

2021-07-20 12:37 UTC, ronagyl commented on ad9083/cfgs/cfg2_64b66b_np8.tcl
> +set ad_project_params(TX_JESD_K) 256
This config file is unused.

2021-07-20 12:37 UTC, ronagyl commented on ad9083/cfgs/cfg3_64b66b_np12.tcl
> +set ad_project_params(TX_JESD_K) 256
This config file is unused. Should be removed.

2021-07-20 12:37 UTC, ronagyl commented on ad9083/cfgs/cfg4_8b10b_np12.tcl
> +set ad_project_params(TX_JESD_K) 32
This config file is unused. Should be removed.

2021-07-21 08:37 UTC, sarpadi commented
done

2021-07-21 08:37 UTC, merged