Logger update
analogdevicesinc/testbenches pull request #128
Opened 2024-11-05 08:26 UTC by IstvanZsSzekely

Update logger functions:
- Logger now supports cascaded hierarchy level prints
- Block design related VIP modules have suitable macros for logging
- Added ADI verbosity levels
- Updated library and testbenches

2024-11-19 21:34 UTC, gastmaier requested changes

2024-11-19 21:34 UTC, gastmaier commented on library/utilities/utils.svh
> +// Macros used in VIPs during elaboration
Could provide more context.
We use macros outside contexts that don't inherit adi_component, mostly outside classes.
It seems that if the $error call is outside an initial block the error *may* be raised during elaboration and not compilation (hit or miss for me).
Nevertheless, any macro call inside begin block should be moved to the class.

This works during elaboration:
```
module
  if (MODE != MODE_SLAVE) begin
     $error("Unsupported mode");
  end
end module
```

This works during elaboration but sformatf isn't evaluated, yielding a blank error on elaborate.log (vivado 2024.1):
```
module
  if (MODE != MODE_SLAVE) begin
    $error($sformatf("Unsupported mode %s", MODE));
  end
end module
```

This is misleading:
```
module
  initial begin : ASSERT_PARAMETERS
    assert (MODE == MODE_SLAVE)
    else   begin
      $error($sformatf("Unsupported mode %s", MODE));
    end
  end : ASSERT_PARAMETERS
end module
```
(Using the macros have the same effect, but showed expanded form for clarity).

2024-11-19 21:47 UTC, gastmaier commented on library/drivers/common/scoreboard.sv
> +        this.info($sformatf("Source transaction received, size: %d - %d", this.source_monitor.mailbox.num(), this.source_byte_stream_size), ADI_VERBOSITY_DEBUG);
Note for other reviewers: the reason for having to have $sformatf is that it is not possible to pass an arbitrary a varying number of keyword in systemverilog.
Normally we use macros to emulate the "**kargs" behaviour, but the scope for the verbosity level is problematic.

2024-11-20 08:47 UTC, IstvanZsSzekely commented on library/utilities/utils.svh
> +
This was left in accidentally, when I was testing some file IO operations. The macro was used for specifying the relative path for the simulation, so it can access files. This is removed now, and probably won't be needed if [this PR](https://github.com/analogdevicesinc/testbenches/pull/129) is merged with absolute pathing, from which it will be safer to get path. Slightly different implementation, but more robust.

2024-11-20 08:56 UTC, IstvanZsSzekely commented on library/utilities/utils.svh
> +// Macros used in VIPs during elaboration
This is something that wasn't tested adequately on the VIP section, this is on me. Thank you for tracking this issue down to the core. Tried a couple of options on how to update the VIP that is instantiated in the block design. 
Like you mentioned, there are 2 different system function calls. One for elaboration and one for simulation. These function calls must not be confused as they are evaluated in different stages. 
Adding macros for these stages seems unnecessary and makes things more complicated than they should be. Using the regular system function calls will ensure that the right function is called and the designer doesn't have to think about it. When printing useful information on the screen, the verbosity levels are disabled in these files, however, I believe that information will be printed far less compared to simulation prints. Linking verbosity option to the block design level outputs doesn't seem to be worth the effort and headache at this point in time.

2024-11-20 09:56 UTC, IstvanZsSzekely commented
Updated and rebased the logger on main. Fixed compatibility issues.

2024-11-20 13:23 UTC, gastmaier approved these changes
Thank you for the update, the errors print in the following format:
```
Error: [ERROR] @ 1425 ns: [SPI Engine Environment.AXI Manager sequencer]  Address : 0000000044a00000; Data mismatch. Read data is : 00010301; expected is 00010300
```
The double error/fatal/info may be redundant, but that's is a nitpick

2024-11-20 14:24 UTC, IstvanZsSzekely commented
> Thank you for the update, the errors print in the following format:
> 
> ```
> Error: [ERROR] @ 1425 ns: [SPI Engine Environment.AXI Manager sequencer]  Address : 0000000044a00000; Data mismatch. Read data is : 00010301; expected is 00010300
> ```
> 
> The double error/fatal/info may be redundant, but that's is a nitpick

When implementing and updating the modules, I haven't checked how are the messages actually printed, I was focusing on function over form. Updated the 3 non-Info messages.

2024-11-20 14:26 UTC, merged