docs: Add ad463x doc support
analogdevicesinc/testbenches pull request #132
Opened 2024-11-12 08:24 UTC by StancaPop

Add documentation support for the AD463X testbench.

2024-11-12 11:59 UTC, IstvanZsSzekely requested changes

2024-11-12 13:16 UTC, StancaPop commented on docs/testbenches/project_based/ad463x/index.rst
> +along with VIPs used for clock & reset, DDR and PS AXI.
Updated.

2024-11-12 13:16 UTC, StancaPop commented on docs/testbenches/project_based/ad463x/index.rst
> +Below are the CPU/Memory interconnects addresses used in this project:
Done.

2024-11-12 13:16 UTC, StancaPop commented on docs/testbenches/project_based/ad463x/index.rst
> +following example:
Updated.

2024-11-12 14:07 UTC, StancaPop commented on docs/testbenches/project_based/ad463x/index.rst
> +followed by custom tests (Sanity, FIFO SPI and Offload SPI tests).
Done.

2024-11-13 08:25 UTC, IstvanZsSzekely approved these changes

2024-11-13 08:50 UTC, merged