Add ad738x doc
analogdevicesinc/testbenches pull request #133
Opened 2024-11-12 14:14 UTC by StancaPop

Add support for ad738x testbenches documentation.

2024-11-12 14:16 UTC, StancaPop commented
v1. Made the branch from the https://github.com/analogdevicesinc/testbenches/tree/add_ad463x_doc branch, waiting for [this](https://github.com/analogdevicesinc/testbenches/pull/132) PR to be merged first.

2024-11-13 13:23 UTC, IstvanZsSzekely requested changes
Replace part number of AD463X with AD738X.

2024-11-13 14:44 UTC, IstvanZsSzekely requested changes

2024-11-14 08:27 UTC, StancaPop commented on docs/testbenches/project_based/ad738x/index.rst
> +* Create the environment
Fixed it. Thank you.

2024-11-14 09:08 UTC, IstvanZsSzekely approved these changes

2024-11-14 09:15 UTC, merged