Added a new testbench for checking the SPI Engine Sleep and Chip Select Instruction delays
analogdevicesinc/testbenches pull request #49
Opened 2023-10-18 14:14 UTC by LBFFilho

This PR creates a separate test, which was used on creating [this other PR to the hdl repo](https://github.com/analogdevicesinc/hdl/pull/1200). The aim of these PRs is to address some incosistencies with the sleep and delay behaviors on the Sleep and Chip Select instructions. To run the tests, simply cd to the testbenches/pulsar_adc_pmdz directory, and run:

`make TST=sleep_delay_test`

For more information about the specifig bug fixes, please look at the PR on the hdl repository:
[SPI Engine: Fixed delay behaviour on Chip-Select and Sleep instructions](https://github.com/analogdevicesinc/hdl/pull/1200)

2023-10-18 14:53 UTC, gastmaier requested changes

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +//
Remove this extra // lines

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +localparam SPI_ENG_ADDR_VERSION       = 32'h0000_0000;
Can we remove the registers not being used?
Ideally, I would rather have a header file in the spi engine, but since the spi engine does not use a header file, that's fine...

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +`define PULSAR_ADC_DMA                  32'h44A3_0000
I would use only localparam, dropping the define

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +localparam PULSAR_ADC_BASE = `PULSAR_ADC_REGMAP;
I would drop the define and set it here directly

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +
Remove extra line

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +
Remove extra line

2023-10-18 14:53 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +
Remove extra line

2023-10-18 15:52 UTC, LBFFilho commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +    // behaviour as per wiki should be 2*cs_activate_delay*(1+CLOCK_DIVIDER), half before and half after cs change
Actually the last of this set of comments is the breakdown of expected behavior, will remove the others

2023-10-18 18:06 UTC, LBFFilho commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +      if (idle && (cmd_d1[15:8] == 8'h31)) begin
This suggestion can be a problem for back-to-back sleep commands. Granted, we currently don't test this on the testbench, but we might test it on the future. I think it's better to keep it as per the original PR

2023-10-18 21:34 UTC, LBFFilho commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +localparam PULSAR_ADC_BASE = `PULSAR_ADC_REGMAP;
I actually had left this half-done on the PR. This is supposed to be used to make the sleep test task's sleep parametrization more legible, but it turns out I left it out on the PR. Will fix it to use it properly, should be better. Otherwise, I can just leave the bitwise expression on the axi write call, but I think it'll be more legible this way.

2023-10-18 21:34 UTC, LBFFilho commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> +localparam SPI_ENG_ADDR_VERSION       = 32'h0000_0000;
I've added a header file with the SPI Engine registers, so that both tests can include it.

2023-10-20 13:49 UTC, gastmaier approved these changes

2023-10-20 13:50 UTC, gastmaier commented
Squash and merge when [#1200](../../hdl/pull/1200) gets approved too

2023-10-23 14:04 UTC, gastmaier commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
>    // Configure the Offload module
Is not configuring the offload module anymore, update comment.

2023-10-24 12:32 UTC, gastmaier approved these changes

2023-10-30 12:54 UTC, merged