DMA Scatter-Gather Testbench
analogdevicesinc/testbenches pull request #54
Opened 2023-10-31 11:25 UTC by podgori

Added a testbench for the Scatter-Gather feature which tests the following:
- 1D (simple) SG transfers
- 2D SG transfers
- Multiple queued SG transfers

2023-10-31 19:42 UTC, gastmaier requested changes
Great work, I only miss a test method to write the descriptor to make the tbs more concise, explaining what the test does and the expected result, and perhaps more interesting tests scenarios, like non contiguous sg transfers, if applicable.

2023-10-31 19:42 UTC, gastmaier commented on dma_sg/tests/test_program_1d.sv
> +    env.ddr_axi_agent.mem_model.backdoor_memory_write_4byte(`DDR_BASE+'h1_0018, `DDR_BASE+'h1_0030,'hF); //next_sg_addr
Could we make the tb more interesting by doing the next_sg_addr sequence non linear, like
0 -> 60 -> 30 -> 90 -> ....
instead of 
0 -> 30-> 60 -> 90 -> ....
updating the pattern and verification accordingly.

2023-10-31 19:42 UTC, gastmaier commented on dma_sg/tests/test_program_1d.sv
> +    env.ddr_axi_agent.mem_model.backdoor_memory_write_4byte(`DDR_BASE+'h1_0054, 'h0FFF,'hF); //x_len
Could we make the tb more interesting and variate the x_len?
From my understanding we are using a scatter and gather to move data in a linear order in this tb, even between descriptors, right?

2023-10-31 19:42 UTC, gastmaier commented on dma_sg/tests/test_program_tr_queue.sv
> +    env.ddr_axi_agent.mem_model.backdoor_memory_write_4byte(`DDR_BASE+'h1_0000, 'h0000,'hF); //flags
Can we make a method write_descriptor that receives the descriptor structure and address as parameters?
It would greatly reduce the length of these tests and improve readability.

2023-10-31 19:42 UTC, gastmaier commented on dma_sg/tests/test_program_tr_queue.sv
> +    //  Test TX DMA and RX DMA in loopback
The purpose of this test is to do 4 unrelated sg tx transfers in queue right? perhaps explain somewhere.

2024-04-23 20:48 UTC, gastmaier commented
@podgori can you check the conflict and resolve the comments?
Feel free to disregard any comment that you don't think is applicable, let's just merge this.

2024-08-23 09:00 UTC, podgori commented
I think I have addressed most of the requested changes, this TB is ready to be merged.

2024-08-23 11:46 UTC, gastmaier approved these changes
Run all tbs on my end successfully.
Thank you for updating the tb.

2024-08-23 12:17 UTC, IstvanZsSzekely requested changes
Other than the clock and reset call position in the stimulus, all is good, test programs pass the run.

2024-08-23 12:17 UTC, IstvanZsSzekely commented on dma_sg/tests/test_program_1d.sv
> +    env.sys_reset();
Starting the clocks and resetting the system should be done before probing (accessing) the DMA cores

2024-08-23 12:17 UTC, IstvanZsSzekely commented on dma_sg/tests/test_program_2d.sv
> +    env.sys_reset();
Same as previously

2024-08-23 12:17 UTC, IstvanZsSzekely commented on dma_sg/tests/test_program_tr_queue.sv
> +    env.sys_reset();
Same as previously

2024-08-26 06:14 UTC, merged