Base design
analogdevicesinc/testbenches pull request #64
Opened 2024-01-30 13:37 UTC by IstvanZsSzekely

Added a base design that can be used as a starting point for any new testbench. 

By default includes: 

 * all the files that are needed for any testbench
 * scoreboard and auxiliary module imports, ready to be integrated
 * new environment file ready to expand the base test harness environment
 * test program that powers up and shuts down the system
 * option to add manual seeding

It is based on #61 which has the updated test harness and #63 which has the monitoring and scoreboard packages defined.

2024-05-17 12:14 UTC, gastmaier requested changes
Minor comments just because if  we want to use this a gold standard should be as clear as possible

2024-05-17 12:14 UTC, gastmaier commented on base/tests/test_program.sv
> +//
Remove these trailing `//` lines

2024-05-17 12:14 UTC, gastmaier commented on base/tests/test_program.sv
> +// Register Maps
Well, there is no register map here.

2024-05-17 12:14 UTC, gastmaier commented on base/tests/test_program.sv
> +    // create environment
Comments should start with uppercase

2024-05-17 12:14 UTC, gastmaier commented on base/Makefile
> +#TESTS += cfg2_fsync:test_frame_delay
Remove all but test_program
```suggestion
#TESTS += cfg1:test_program
```

2024-05-20 13:27 UTC, IstvanZsSzekely commented on base/tests/test_program.sv
> +    setLoggerVerbosity(250);
The verbosity values are arbitrary in most of the designs, this is a known issue, I felt like there are other more pressing issues at the moment that need to be fixed. We'll be looking into this soon enough, as it affects the documentation as well.

2024-05-24 13:40 UTC, gastmaier approved these changes

2024-05-27 06:59 UTC, merged