i3c_controller: Add testbench project
analogdevicesinc/testbenches pull request #66
Opened 2024-02-05 15:29 UTC by gastmaier

Standalone testbench to assert the implemented features.
Tests https://github.com/analogdevicesinc/hdl/pull/1267

2024-02-06 07:33 UTC, IstvanZsSzekely requested changes
Notes for a future update PR:
Register field accesses should be included in a registermap file for ease of access and readability. This way it'll be less prone to user error. The I3C Controller instructions should still be build using the field accessors, and be used as they currently are. 
Base address definitions in system_bd, and pass values down to the testbench. In case of a bd change, these will be updated automatically. 
AXI Interrupt Controller: when someone gets to implement the controller for the testbench, use it instead.

2024-02-06 07:33 UTC, IstvanZsSzekely commented on i3c_controller/tests/test_program.sv
> +    #TIMEOUT \
Please update the # wait command with a time frame, such as ns, or us. This will enforce correct operation of the testbench in case someone tries to replicate it in a different testbench with a different time unit. Other option you can consider is a clock edge counter. 
```suggestion
    #``TIMEOUT``ns \
    // or
    repeat(TIMEOUT) @(posedge clk); // where clk can be a parameter
```

2024-02-06 07:33 UTC, IstvanZsSzekely commented on i3c_controller/tests/test_program.sv
> +  repeat (5) @(negedge i3c_controller_0_sda);
Wait for negedge one data line or clock line?

2024-02-06 07:33 UTC, IstvanZsSzekely commented on i3c_controller/tests/test_program.sv
> +    @(posedge i3c_clk);
I see you have 2 clocks in the system, i3c_clk (sys_cpu_clk) and i3c_controller_0_scl. 
Do they have the same frequency? Is this the right clock here?

2024-03-07 16:55 UTC, gastmaier commented on i3c_controller/tests/test_program.sv
> +    #TIMEOUT \
Done

2024-03-07 16:55 UTC, gastmaier commented on i3c_controller/tests/test_program.sv
> +    @(posedge i3c_clk);
The SCL is the clock on the bus and is not a "true" clock but a modulated signal.
This method mocks an acknowledgment by the peripheral during the ACK-bit and RX T-bit yielded by the controller.
It's purpose is to simplify the TB, without this I would have to make a method call at every byte transferred during the TB.
It's fine to have this running on the system-clock, it just watches the states of the internal state machine.
However, it's indeed janky.
Added comment to clarify.

2024-03-07 16:55 UTC, gastmaier commented on i3c_controller/tests/test_program.sv
> +  repeat (5) @(negedge i3c_controller_0_sda);
Data line, here I'm counting 5 acknowledge bits asserted by the controller.
The SDA signal is split into SDI and SDO. The TB forces SDI low to mock a write of 8 'h00 bytes, between these bytes there is always ACK bit, that in this case is acknowledged by the controller.
Add comment to clarify.

2024-03-12 19:58 UTC, gastmaier commented
V2
Update tb to reflect [#1267 - V4](https://github.com/analogdevicesinc/hdl/pull/1267).
Update I3C SDA from input to inout.
Suffix delays with ns.
Add basic offload assertion.
Drive SDA lane instead of forcing SDI signal.
Removed DMA and PWM from sample project, assert offload axi and trigger directly.

Minor:
Removed second declaration of dev_char_data.
Remove delays between tasks, since it might mask issues regarding cmd sequences.
Update waveform with the renamed signals

Not changed:
env.sys_reset: requires 1ee12fdf (not on main).

2024-03-13 07:36 UTC, IstvanZsSzekely commented
Checked the updated code, did a build to see it passing, everything seems to be working well.
I'll make a CI build, since I'm I saw in the output some errors that were created by you, which are actually not errors, and I'm not sure if the CI accepts any kind of output message that has a word error or even fail. 
I'll come back with and update when it's ready.

2024-03-14 07:40 UTC, IstvanZsSzekely approved these changes
CI build passed with no error, which is a good to know. 
Error, failed and such keywords are usable in INFO status prints.

2024-04-12 12:21 UTC, merged