Use axi_pwm_gen package in all the testbenches
analogdevicesinc/testbenches pull request #70
Opened 2024-02-12 15:45 UTC by StancaPop

Use the axi_pwm_gen.pkg across all the testbenches, delete the unnecessary delays related to pwm axi_writes and small cosmetic changes.

2024-02-15 06:48 UTC, IstvanZsSzekely requested changes
Most of it seems good, doing some builds to check everything. Requesting to check a missing edit.

2024-02-15 06:48 UTC, IstvanZsSzekely commented on ad7616/tests/test_program_pi.sv
> +    axi_write (AXI_PWMGEN + GetAddrs(REG_PULSE_0_PERIOD), `SET_REG_PULSE_0_PERIOD_PULSE_0_PERIOD('h64)); // set PWM period
Something seems to be missing here.

2024-02-15 06:48 UTC, IstvanZsSzekely commented on ad7616/tests/test_program_pi.sv
> +    axi_write (AXI_PWMGEN + GetAddrs(REG_PULSE_0_PERIOD), `SET_REG_PULSE_0_PERIOD_PULSE_0_PERIOD('h64)); // set PWM period
axi_write (AXI_PWMGEN + 32'h00000080, 'h1);

2024-02-15 07:52 UTC, IstvanZsSzekely requested changes

2024-02-15 07:52 UTC, IstvanZsSzekely commented on ad7606x/tests/test_program.sv
> +    axi_write (`AXI_PWMGEN + GetAddrs(REG_RSTN), `SET_REG_RSTN_LOAD_CONFIG(1)); // load AXI_PWM_GEN configuration
This setup doesn't seem to work for me. Tried a couple of the reset/load config command configurations, with no luck. Did this work for you?

2024-02-15 12:12 UTC, StancaPop commented on ad7616/tests/test_program_pi.sv
> +    axi_write (AXI_PWMGEN + GetAddrs(REG_PULSE_0_PERIOD), `SET_REG_PULSE_0_PERIOD_PULSE_0_PERIOD('h64)); // set PWM period
Yes, I discarded that register write, as it doesn't affect the timing and functionality. I don't find it necessary.

2024-02-20 13:17 UTC, IstvanZsSzekely commented on ad7606x/tests/test_program.sv
> +    axi_write (`AXI_PWMGEN + GetAddrs(REG_RSTN), `SET_REG_RSTN_LOAD_CONFIG(1)); // load AXI_PWM_GEN configuration
Rechecked the testbench in a clean repository, and now it's working for me as well. Might have had some residual files remaining that caused the issue.

2024-02-20 13:18 UTC, IstvanZsSzekely approved these changes
Testbenches are working as expected.

2024-02-20 13:29 UTC, merged