Add missing regmap packages & integrate them in SPI Engine testbenches
analogdevicesinc/testbenches pull request #85
Opened 2024-03-27 10:41 UTC by StancaPop

This PR contains the following updates:

- Add the axi_ad7616 regmap package and integrate it in ad7616 testbench.
- Update the existing regmap package of spi_engine and integrate it in ad463x, ad7616 and pulsar_adc_pmdz testbenches.
- Integrate the clkgen regmap package in ad463x, ad7616 and pulsar_adc_pmdz testbenches.

2024-03-27 11:32 UTC, IstvanZsSzekely requested changes

2024-03-27 11:32 UTC, IstvanZsSzekely commented on ad7616/tests/test_program_si.sv
> -  axi_write (AD7616_BASE + AD7616_CNVST_RATE, 32'h00000128);
Why is this part left out/not updated, like the rest of the commands?

2024-03-27 11:32 UTC, IstvanZsSzekely commented on pulsar_adc_pmdz/tests/test_program.sv
> -    @(posedge pulsar_adc_irq); // TODO: Make sure irq resets even the source remain active after clearing the IRQ register
Is this TODO part actually done?

2024-03-27 11:32 UTC, IstvanZsSzekely commented on pulsar_adc_pmdz/tests/test_sleep_delay.sv
> -    @(posedge pulsar_adc_irq); // TODO: Make sure irq resets even the source remain active after clearing the IRQ register
Same as previous

2024-03-27 11:43 UTC, StancaPop commented on pulsar_adc_pmdz/tests/test_program.sv
> -    @(posedge pulsar_adc_irq); // TODO: Make sure irq resets even the source remain active after clearing the IRQ register
This old comment has been propagated in a lot of SPI Engine related testbenches due to copy-paste of entire sections of the testbench. 

We should delete it from ad463x, too, after checking there are no irq issues.

2024-03-28 10:58 UTC, IstvanZsSzekely approved these changes
Tested the affected projects, all work.

2024-03-28 10:59 UTC, merged