Define the base addresses at block design level
analogdevicesinc/testbenches pull request #90
Opened 2024-04-03 09:01 UTC by StancaPop

Definition of base addresses up until this point happened at both block design and testbench level, which could lead to errors. 

Define the address at block design level and pass the parameter as definition to the testbench.

2024-04-04 06:44 UTC, IstvanZsSzekely requested changes

2024-04-04 06:44 UTC, IstvanZsSzekely commented on ad_quadmxfe1_ebz/tests/test_program.sv
> +  xcvr TX_XCVR_BA;
RX and TX xcvr are classes in here. The base address should be all in uppercase as they are defines, and class names left as lowercase without the _BA suffix.

2024-04-04 06:44 UTC, IstvanZsSzekely commented on adrv9001/tests/test_program.sv
> +  parameter BASE = `AXI_ADRV9001_BA;
Instead of BASE use the ADRV9001_BA to avoid confusion.

2024-04-04 06:44 UTC, IstvanZsSzekely commented on mxfe/tests/test_program.sv
> +  xcvr TX_XCVR_BA;
Same as the other.

2024-04-04 07:25 UTC, StancaPop commented on ad_quadmxfe1_ebz/tests/test_program.sv
> +  xcvr TX_XCVR_BA;
Done.

2024-04-04 07:25 UTC, StancaPop commented on adrv9001/tests/test_program.sv
> +  parameter BASE = `AXI_ADRV9001_BA;
Done.

2024-04-04 07:25 UTC, StancaPop commented on mxfe/tests/test_program.sv
> +  xcvr TX_XCVR_BA;
Done.

2024-04-04 07:28 UTC, StancaPop commented on adrv9001/tests/test_program.sv
> +  parameter BASE = `AXI_ADRV9001_BA;
Made the same changes in fmcomms2.

2024-04-08 10:23 UTC, StancaPop commented
The jesd_loopback testbench fails for cfg6, but the error doesn't come from this update.

[ERROR] 89535 ns   Address : 0000000044a90314; Data mismatch. Read data is : 00000000; expected is 1f3f8000
found in /testbenches/common/sv/m_axi_sequencer.sv:107

2024-04-09 07:21 UTC, IstvanZsSzekely approved these changes

2024-04-09 08:13 UTC, merged