Differentiate function calls from variables
analogdevicesinc/testbenches pull request #95
Opened 2024-04-12 11:36 UTC by StancaPop

Add parentheses to function calls to differentiate them from variables for readability.

2024-04-12 12:32 UTC, IstvanZsSzekely requested changes

2024-04-12 12:32 UTC, IstvanZsSzekely commented on data_offload_2/tests/test_program.sv
> +    `endif
This part should be left as is. The `ifdef part signals a conditional statement that is evaluated at compilation time, and the dut... part runs in the same scope as the previous statement, hence the same padding.

2024-04-16 07:09 UTC, StancaPop commented on ad7606x/tests/test_program.sv
>    sanity_test;
Done.

2024-04-16 07:09 UTC, StancaPop commented on data_offload_2/tests/test_program.sv
> +    `endif
Done.

2024-04-16 07:51 UTC, IstvanZsSzekely requested changes

2024-04-16 07:51 UTC, IstvanZsSzekely commented on i3c_controller/tests/test_program.sv
> -endtask
I think this is a mistake.

2024-04-16 10:12 UTC, StancaPop commented on i3c_controller/tests/test_program.sv
> -endtask
Yes, I fixed it in the meantime.

2024-04-16 10:49 UTC, IstvanZsSzekely approved these changes

2024-04-16 11:54 UTC, merged